// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiy3IU8-Enn3zf8p7crwlzmRcXb5BPurQ',
    appId: '1:303209621681:web:257dee6b310eaa33bd9a90',
    messagingSenderId: '303209621681',
    projectId: 'bmiorder-db8c9',
    authDomain: 'bmiorder-db8c9.firebaseapp.com',
    storageBucket: 'bmiorder-db8c9.appspot.com',
    measurementId: 'G-BC54VEVHW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfrvcEVDt-zfdp8tct3XS5A2Caor2rrJA',
    appId: '1:303209621681:android:b3874527fcc298a4bd9a90',
    messagingSenderId: '303209621681',
    projectId: 'bmiorder-db8c9',
    storageBucket: 'bmiorder-db8c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0jJIrjGumWR1Q_WmHvQjoGhI1nHNgqV8',
    appId: '1:303209621681:ios:0cce6ac18dbc953abd9a90',
    messagingSenderId: '303209621681',
    projectId: 'bmiorder-db8c9',
    storageBucket: 'bmiorder-db8c9.appspot.com',
    iosClientId: '303209621681-5319ek1ge46cpsuldnk54ii3hh9f956c.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
